/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mKaES5lq7bZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function InitialScreen() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2 font-bold text-xl" prefetch={false}>
          <LeafIcon className="w-6 h-6" />
          <span>FoodSaver</span>
        </Link>
        <div className="relative flex-1 max-w-md mx-6">
          <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search for products..."
            className="w-full rounded-full bg-primary-foreground/10 pl-10 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:bg-primary-foreground/20"
          />
        </div>
        <Link href="#" className="relative" prefetch={false}>
          <ShoppingCartIcon className="w-6 h-6" />
          <Badge className="absolute -top-2 -right-2 bg-accent text-accent-foreground rounded-full px-2 py-0.5 text-xs font-medium">
            3
          </Badge>
        </Link>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-12 md:py-20">
          <div className="container px-4 md:px-6 grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-5xl font-bold">Explore Our Fresh Produce and Pantry Items</h1>
              <p className="text-muted-foreground text-lg">
                Browse our selection of high-quality, sustainably sourced products delivered straight to your door.
              </p>
            </div>
            <img src="/placeholder.svg" width={600} height={400} alt="Hero Image" className="rounded-lg object-cover" />
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8">
              <div className="flex items-center justify-between">
                <h2 className="text-2xl md:text-3xl font-bold">Featured Products</h2>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  View All
                </Link>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Apples (5 lbs)</h3>
                      <p className="text-muted-foreground">Fresh, crisp apples from local orchards.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$10.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-08-31</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $12.99 (-15% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Carrots (10 lbs)</h3>
                      <p className="text-muted-foreground">Freshly harvested, crunchy carrots.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$8.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-09-15</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $9.99 (-10% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Spinach (1 lb)</h3>
                      <p className="text-muted-foreground">Nutrient-rich, fresh spinach leaves.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$3.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-08-01</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $4.99 (-20% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Tomatoes (5 lbs)</h3>
                      <p className="text-muted-foreground">Juicy, vine-ripened tomatoes.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$7.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-09-01</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $8.99 (-11% discount)</p>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-20">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8">
              <div className="flex items-center justify-between">
                <h2 className="text-2xl md:text-3xl font-bold">Our Mission: Reduce Food Waste</h2>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  Learn More
                </Link>
              </div>
              <div className="grid md:grid-cols-2 gap-8">
                <div className="space-y-4">
                  <p className="text-muted-foreground text-lg">
                    At FoodSaver, we're on a mission to reduce food waste and support sustainable food systems. By
                    connecting you with local wholesalers, we ensure that fresh produce and pantry items are delivered
                    directly to your door, minimizing the time between harvest and consumption.
                  </p>
                  <p className="text-muted-foreground text-lg">
                    Our platform prioritizes transparency, allowing you to track the origin and journey of your food. We
                    work closely with our partners to implement best practices for harvesting, storage, and
                    distribution, ensuring that your order arrives in peak condition.
                  </p>
                </div>
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="Reduce Food Waste"
                  className="rounded-lg object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8">
              <div className="flex items-center justify-between">
                <h2 className="text-2xl md:text-3xl font-bold">Explore Our Products</h2>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Apples (5 lbs)</h3>
                      <p className="text-muted-foreground">Fresh, crisp apples from local orchards.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$10.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-08-31</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $12.99 (-15% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Carrots (10 lbs)</h3>
                      <p className="text-muted-foreground">Freshly harvested, crunchy carrots.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$8.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-09-15</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $9.99 (-10% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Spinach (1 lb)</h3>
                      <p className="text-muted-foreground">Nutrient-rich, fresh spinach leaves.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$3.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-08-01</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $4.99 (-20% discount)</p>
                    </div>
                  </CardContent>
                </Card>
                <Card className="border-0 shadow-lg">
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={300}
                      height={200}
                      alt="Product Image"
                      className="rounded-t-lg object-cover w-full aspect-[3/2]"
                    />
                    <div className="p-4 space-y-2">
                      <h3 className="text-lg font-semibold">Organic Tomatoes (5 lbs)</h3>
                      <p className="text-muted-foreground">Juicy, vine-ripened tomatoes.</p>
                      <div className="flex items-center justify-between">
                        <span className="text-2xl font-bold">$7.99</span>
                        <Button size="sm">Add to Cart</Button>
                      </div>
                      <p className="text-muted-foreground text-sm">Expires: 2024-09-01</p>
                      <p className="text-muted-foreground text-sm">Regular Price: $8.99 (-11% discount)</p>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-8 px" />
    </div>
  )
}

function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
